# -*- coding: utf-8 -*-
"""automate_nelson

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ce2qCL-YHOGa065DC8BdZ_9vIW1tx01N
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
import os

# ============================
# 1. Load raw dataset
# ============================
raw_file = "StudentsPerformance.csv"   # ganti sesuai lokasi datasetmu

df = pd.read_csv(raw_file)
print("Dataset berhasil dibaca.")
print(df.head())
print(df.info())

# ============================
# 2. Tentukan kolom numerik & kategorikal
# ============================
num_cols = ['math score', 'reading score', 'writing score']
cat_cols = ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']

# ============================
# 3. Buat transformer
# ============================
scaler = StandardScaler()
encoder = OneHotEncoder(sparse_output=False, drop='first')

transformer = ColumnTransformer([
    ('num', scaler, num_cols),
    ('cat', encoder, cat_cols)
])

# ============================
# 4. Jalankan preprocessing
# ============================
processed = transformer.fit_transform(df)

# Nama kolom hasil encoding
encoded_cols = transformer.named_transformers_['cat'].get_feature_names_out(cat_cols)

# Gabungkan semua kolom
final_columns = num_cols + list(encoded_cols)

# INI YANG KAMU MINTA → NAMA DATAFRAME AKHIR = df_cleaned
df_cleaned = pd.DataFrame(processed, columns=final_columns)

# ============================
# 5. Simpan hasil akhir
# ============================
output_folder = "preprocessing/namadataset_preprocessing"
os.makedirs(output_folder, exist_ok=True)

output_file = os.path.join(output_folder, "StudentsPerformance_cleaned.csv")

df_cleaned.to_csv(output_file, index=False)

print(f"PREPROCESSING SELESAI → File tersimpan di: {output_file}")